scenario:
  type: grid
  grid_size: 5
  vehicles_per_hour: 1000
  accident_probability: 0.02
  random_seed: 42

simulation:
  backend: sumo
  step_length: 1.0

optimizer:
  algorithm: pso
  iterations: 100
  population_size: 20

objectives:
  selected: avg_travel_time
  available:
    avg_travel_time: "Minimize the average travel time for all vehicles"
    total_delay: "Minimize the total vehicle delay at intersections"
    congestion: "Reduce total system congestion"
    throughput: "Maximize total throughput"
    emissions: "Minimize estimated emissions"

sensitivity:
  enabled: true
  parameters:
    traffic_volume:
      min: 500
      max: 2000
    accident_probability:
      min: 0.0
      max: 0.05
    signal_min_time:
      min: 10
      max: 30